---
development:
  cloud_name: dqxyawat4
  api_key: '497113198722324'
  api_secret: zed3x6JFJx4golbSLJBCHJ2GcYg
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dqxyawat4
  api_key: '497113198722324'
  api_secret: zed3x6JFJx4golbSLJBCHJ2GcYg
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dqxyawat4
  api_key: '497113198722324'
  api_secret: zed3x6JFJx4golbSLJBCHJ2GcYg
  enhance_image_tag: true
  static_file_support: false
